# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parse Insta Clone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parse Insta Clone

  pod 'Parse'
  # parseplatform.github.io

  #target 'Parse Insta Clone' do
    #pod 'OneSignal', '>= 2.6.2', '< 3.0'
  #end

  target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
  end


  target 'Parse Insta CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Parse Insta CloneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
